// source: bottle/fulfillment/v1/tax_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var bottle_fulfillment_v1_order_pb = require('../../../bottle/fulfillment/v1/order_pb.js');
goog.object.extend(proto, bottle_fulfillment_v1_order_pb);
var bottle_fulfillment_v1_tax_line_pb = require('../../../bottle/fulfillment/v1/tax_line_pb.js');
goog.object.extend(proto, bottle_fulfillment_v1_tax_line_pb);
goog.exportSymbol('proto.bottle.fulfillment.v1.TaxCalculateRequest', null, global);
goog.exportSymbol('proto.bottle.fulfillment.v1.TaxCalculateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.fulfillment.v1.TaxCalculateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.fulfillment.v1.TaxCalculateRequest.displayName = 'proto.bottle.fulfillment.v1.TaxCalculateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.fulfillment.v1.TaxCalculateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.fulfillment.v1.TaxCalculateResponse.displayName = 'proto.bottle.fulfillment.v1.TaxCalculateResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.fulfillment.v1.TaxCalculateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.fulfillment.v1.TaxCalculateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    order: (f = msg.getOrder()) && bottle_fulfillment_v1_order_pb.Order.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.fulfillment.v1.TaxCalculateRequest}
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.fulfillment.v1.TaxCalculateRequest;
  return proto.bottle.fulfillment.v1.TaxCalculateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.fulfillment.v1.TaxCalculateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.fulfillment.v1.TaxCalculateRequest}
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = new bottle_fulfillment_v1_order_pb.Order;
      reader.readMessage(value,bottle_fulfillment_v1_order_pb.Order.deserializeBinaryFromReader);
      msg.setOrder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.fulfillment.v1.TaxCalculateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.fulfillment.v1.TaxCalculateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrder();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      bottle_fulfillment_v1_order_pb.Order.serializeBinaryToWriter
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.fulfillment.v1.TaxCalculateRequest} returns this
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Order order = 2;
 * @return {?proto.bottle.fulfillment.v1.Order}
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.prototype.getOrder = function() {
  return /** @type{?proto.bottle.fulfillment.v1.Order} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_order_pb.Order, 2));
};


/**
 * @param {?proto.bottle.fulfillment.v1.Order|undefined} value
 * @return {!proto.bottle.fulfillment.v1.TaxCalculateRequest} returns this
*/
proto.bottle.fulfillment.v1.TaxCalculateRequest.prototype.setOrder = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.fulfillment.v1.TaxCalculateRequest} returns this
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.prototype.clearOrder = function() {
  return this.setOrder(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.fulfillment.v1.TaxCalculateRequest.prototype.hasOrder = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.fulfillment.v1.TaxCalculateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.fulfillment.v1.TaxCalculateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    order: (f = msg.getOrder()) && bottle_fulfillment_v1_order_pb.Order.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.fulfillment.v1.TaxCalculateResponse}
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.fulfillment.v1.TaxCalculateResponse;
  return proto.bottle.fulfillment.v1.TaxCalculateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.fulfillment.v1.TaxCalculateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.fulfillment.v1.TaxCalculateResponse}
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = new bottle_fulfillment_v1_order_pb.Order;
      reader.readMessage(value,bottle_fulfillment_v1_order_pb.Order.deserializeBinaryFromReader);
      msg.setOrder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.fulfillment.v1.TaxCalculateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.fulfillment.v1.TaxCalculateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrder();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      bottle_fulfillment_v1_order_pb.Order.serializeBinaryToWriter
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.fulfillment.v1.TaxCalculateResponse} returns this
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Order order = 2;
 * @return {?proto.bottle.fulfillment.v1.Order}
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.prototype.getOrder = function() {
  return /** @type{?proto.bottle.fulfillment.v1.Order} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_order_pb.Order, 2));
};


/**
 * @param {?proto.bottle.fulfillment.v1.Order|undefined} value
 * @return {!proto.bottle.fulfillment.v1.TaxCalculateResponse} returns this
*/
proto.bottle.fulfillment.v1.TaxCalculateResponse.prototype.setOrder = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.fulfillment.v1.TaxCalculateResponse} returns this
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.prototype.clearOrder = function() {
  return this.setOrder(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.fulfillment.v1.TaxCalculateResponse.prototype.hasOrder = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.bottle.fulfillment.v1);
