// source: bottle/core/v1/bottle.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var bottle_account_v1_events_pb = require('../../../bottle/account/v1/events_pb.js');
goog.object.extend(proto, bottle_account_v1_events_pb);
var bottle_assembly_v1_events_pb = require('../../../bottle/assembly/v1/events_pb.js');
goog.object.extend(proto, bottle_assembly_v1_events_pb);
var bottle_core_v1_testing_pb = require('../../../bottle/core/v1/testing_pb.js');
goog.object.extend(proto, bottle_core_v1_testing_pb);
var bottle_fulfillment_v1_events_pb = require('../../../bottle/fulfillment/v1/events_pb.js');
goog.object.extend(proto, bottle_fulfillment_v1_events_pb);
var bottle_fulfillment_v1_order_verification_service_pb = require('../../../bottle/fulfillment/v1/order_verification_service_pb.js');
goog.object.extend(proto, bottle_fulfillment_v1_order_verification_service_pb);
var bottle_inventory_v1_events_pb = require('../../../bottle/inventory/v1/events_pb.js');
goog.object.extend(proto, bottle_inventory_v1_events_pb);
var bottle_support_v1_events_pb = require('../../../bottle/support/v1/events_pb.js');
goog.object.extend(proto, bottle_support_v1_events_pb);
var bottle_templates_v1_events_pb = require('../../../bottle/templates/v1/events_pb.js');
goog.object.extend(proto, bottle_templates_v1_events_pb);
goog.exportSymbol('proto.bottle.core.v1.Bottle', null, global);
goog.exportSymbol('proto.bottle.core.v1.Bottle.ResourceCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.core.v1.Bottle = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.bottle.core.v1.Bottle.oneofGroups_);
};
goog.inherits(proto.bottle.core.v1.Bottle, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.core.v1.Bottle.displayName = 'proto.bottle.core.v1.Bottle';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.bottle.core.v1.Bottle.oneofGroups_ = [[4,22,23,24,6,7,20,21,8,9,18,19,10,11,12,31,13,14,28,29,15,30,25,26,32,16,17,33,27]];

/**
 * @enum {number}
 */
proto.bottle.core.v1.Bottle.ResourceCase = {
  RESOURCE_NOT_SET: 0,
  ORDER_CREATED: 4,
  ORDER_UPDATED: 22,
  ORDER_VERIFICATION_REQUEST: 23,
  ORDER_VERIFICATION_RESPONSE: 24,
  TRIBBLE_FAILED: 6,
  USER_CREATED: 7,
  USER_DELETED: 20,
  USER_UPDATED: 21,
  PASSWORD_CHANGED: 8,
  PASSWORD_RESET: 9,
  TWO_FACTOR_REQUESTED: 18,
  TWO_FACTOR_RECOVERY_CODE_USED: 19,
  ORGANIZATION_CREATED: 10,
  ORGANIZATION_JOINED: 11,
  ORGANIZATION_LEFT: 12,
  BUILD_CANCELLED: 31,
  BUILD_CREATED: 13,
  BUILD_UPDATED: 14,
  BUILD_PICKED: 28,
  COMPONENT_DEMAND_UPDATED: 29,
  COMPONENT_AVAILABILITY_UPDATED: 15,
  SKU_DETAILS_UPDATED: 30,
  PART_CREATED: 25,
  PART_UPDATED: 26,
  COMPONENT_KIT_CHANGED: 32,
  QUESTION_CREATED: 16,
  MACRO_APPLIED: 17,
  TEMPLATED_EMAIL: 33,
  TEST_EVENT: 27
};

/**
 * @return {proto.bottle.core.v1.Bottle.ResourceCase}
 */
proto.bottle.core.v1.Bottle.prototype.getResourceCase = function() {
  return /** @type {proto.bottle.core.v1.Bottle.ResourceCase} */(jspb.Message.computeOneofCase(this, proto.bottle.core.v1.Bottle.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.core.v1.Bottle.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.core.v1.Bottle.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.core.v1.Bottle} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.core.v1.Bottle.toObject = function(includeInstance, msg) {
  var f, obj = {
    timestamp: jspb.Message.getFieldWithDefault(msg, 1, 0),
    requestId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    source: jspb.Message.getFieldWithDefault(msg, 3, ""),
    orderCreated: (f = msg.getOrderCreated()) && bottle_fulfillment_v1_events_pb.OrderCreated.toObject(includeInstance, f),
    orderUpdated: (f = msg.getOrderUpdated()) && bottle_fulfillment_v1_events_pb.OrderUpdated.toObject(includeInstance, f),
    orderVerificationRequest: (f = msg.getOrderVerificationRequest()) && bottle_fulfillment_v1_order_verification_service_pb.OrderVerificationRequest.toObject(includeInstance, f),
    orderVerificationResponse: (f = msg.getOrderVerificationResponse()) && bottle_fulfillment_v1_order_verification_service_pb.OrderVerificationResponse.toObject(includeInstance, f),
    tribbleFailed: (f = msg.getTribbleFailed()) && bottle_fulfillment_v1_events_pb.TribbleFailed.toObject(includeInstance, f),
    userCreated: (f = msg.getUserCreated()) && bottle_account_v1_events_pb.UserCreated.toObject(includeInstance, f),
    userDeleted: (f = msg.getUserDeleted()) && bottle_account_v1_events_pb.UserDeleted.toObject(includeInstance, f),
    userUpdated: (f = msg.getUserUpdated()) && bottle_account_v1_events_pb.UserUpdated.toObject(includeInstance, f),
    passwordChanged: (f = msg.getPasswordChanged()) && bottle_account_v1_events_pb.PasswordChanged.toObject(includeInstance, f),
    passwordReset: (f = msg.getPasswordReset()) && bottle_account_v1_events_pb.PasswordReset.toObject(includeInstance, f),
    twoFactorRequested: (f = msg.getTwoFactorRequested()) && bottle_account_v1_events_pb.TwoFactorRequested.toObject(includeInstance, f),
    twoFactorRecoveryCodeUsed: (f = msg.getTwoFactorRecoveryCodeUsed()) && bottle_account_v1_events_pb.TwoFactorRecoveryCodeUsed.toObject(includeInstance, f),
    organizationCreated: (f = msg.getOrganizationCreated()) && bottle_account_v1_events_pb.OrganizationCreated.toObject(includeInstance, f),
    organizationJoined: (f = msg.getOrganizationJoined()) && bottle_account_v1_events_pb.OrganizationJoined.toObject(includeInstance, f),
    organizationLeft: (f = msg.getOrganizationLeft()) && bottle_account_v1_events_pb.OrganizationLeft.toObject(includeInstance, f),
    buildCancelled: (f = msg.getBuildCancelled()) && bottle_assembly_v1_events_pb.BuildCancelled.toObject(includeInstance, f),
    buildCreated: (f = msg.getBuildCreated()) && bottle_assembly_v1_events_pb.BuildCreated.toObject(includeInstance, f),
    buildUpdated: (f = msg.getBuildUpdated()) && bottle_assembly_v1_events_pb.BuildUpdated.toObject(includeInstance, f),
    buildPicked: (f = msg.getBuildPicked()) && bottle_assembly_v1_events_pb.BuildPicked.toObject(includeInstance, f),
    componentDemandUpdated: (f = msg.getComponentDemandUpdated()) && bottle_assembly_v1_events_pb.ComponentDemandUpdated.toObject(includeInstance, f),
    componentAvailabilityUpdated: (f = msg.getComponentAvailabilityUpdated()) && bottle_inventory_v1_events_pb.ComponentAvailabilityUpdated.toObject(includeInstance, f),
    skuDetailsUpdated: (f = msg.getSkuDetailsUpdated()) && bottle_inventory_v1_events_pb.SkuDetailsUpdated.toObject(includeInstance, f),
    partCreated: (f = msg.getPartCreated()) && bottle_inventory_v1_events_pb.PartCreated.toObject(includeInstance, f),
    partUpdated: (f = msg.getPartUpdated()) && bottle_inventory_v1_events_pb.PartUpdated.toObject(includeInstance, f),
    componentKitChanged: (f = msg.getComponentKitChanged()) && bottle_inventory_v1_events_pb.ComponentKitChanged.toObject(includeInstance, f),
    questionCreated: (f = msg.getQuestionCreated()) && bottle_support_v1_events_pb.QuestionCreated.toObject(includeInstance, f),
    macroApplied: (f = msg.getMacroApplied()) && bottle_support_v1_events_pb.MacroApplied.toObject(includeInstance, f),
    templatedEmail: (f = msg.getTemplatedEmail()) && bottle_templates_v1_events_pb.TemplatedEmail.toObject(includeInstance, f),
    testEvent: (f = msg.getTestEvent()) && bottle_core_v1_testing_pb.TestEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.core.v1.Bottle}
 */
proto.bottle.core.v1.Bottle.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.core.v1.Bottle;
  return proto.bottle.core.v1.Bottle.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.core.v1.Bottle} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.core.v1.Bottle}
 */
proto.bottle.core.v1.Bottle.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    case 4:
      var value = new bottle_fulfillment_v1_events_pb.OrderCreated;
      reader.readMessage(value,bottle_fulfillment_v1_events_pb.OrderCreated.deserializeBinaryFromReader);
      msg.setOrderCreated(value);
      break;
    case 22:
      var value = new bottle_fulfillment_v1_events_pb.OrderUpdated;
      reader.readMessage(value,bottle_fulfillment_v1_events_pb.OrderUpdated.deserializeBinaryFromReader);
      msg.setOrderUpdated(value);
      break;
    case 23:
      var value = new bottle_fulfillment_v1_order_verification_service_pb.OrderVerificationRequest;
      reader.readMessage(value,bottle_fulfillment_v1_order_verification_service_pb.OrderVerificationRequest.deserializeBinaryFromReader);
      msg.setOrderVerificationRequest(value);
      break;
    case 24:
      var value = new bottle_fulfillment_v1_order_verification_service_pb.OrderVerificationResponse;
      reader.readMessage(value,bottle_fulfillment_v1_order_verification_service_pb.OrderVerificationResponse.deserializeBinaryFromReader);
      msg.setOrderVerificationResponse(value);
      break;
    case 6:
      var value = new bottle_fulfillment_v1_events_pb.TribbleFailed;
      reader.readMessage(value,bottle_fulfillment_v1_events_pb.TribbleFailed.deserializeBinaryFromReader);
      msg.setTribbleFailed(value);
      break;
    case 7:
      var value = new bottle_account_v1_events_pb.UserCreated;
      reader.readMessage(value,bottle_account_v1_events_pb.UserCreated.deserializeBinaryFromReader);
      msg.setUserCreated(value);
      break;
    case 20:
      var value = new bottle_account_v1_events_pb.UserDeleted;
      reader.readMessage(value,bottle_account_v1_events_pb.UserDeleted.deserializeBinaryFromReader);
      msg.setUserDeleted(value);
      break;
    case 21:
      var value = new bottle_account_v1_events_pb.UserUpdated;
      reader.readMessage(value,bottle_account_v1_events_pb.UserUpdated.deserializeBinaryFromReader);
      msg.setUserUpdated(value);
      break;
    case 8:
      var value = new bottle_account_v1_events_pb.PasswordChanged;
      reader.readMessage(value,bottle_account_v1_events_pb.PasswordChanged.deserializeBinaryFromReader);
      msg.setPasswordChanged(value);
      break;
    case 9:
      var value = new bottle_account_v1_events_pb.PasswordReset;
      reader.readMessage(value,bottle_account_v1_events_pb.PasswordReset.deserializeBinaryFromReader);
      msg.setPasswordReset(value);
      break;
    case 18:
      var value = new bottle_account_v1_events_pb.TwoFactorRequested;
      reader.readMessage(value,bottle_account_v1_events_pb.TwoFactorRequested.deserializeBinaryFromReader);
      msg.setTwoFactorRequested(value);
      break;
    case 19:
      var value = new bottle_account_v1_events_pb.TwoFactorRecoveryCodeUsed;
      reader.readMessage(value,bottle_account_v1_events_pb.TwoFactorRecoveryCodeUsed.deserializeBinaryFromReader);
      msg.setTwoFactorRecoveryCodeUsed(value);
      break;
    case 10:
      var value = new bottle_account_v1_events_pb.OrganizationCreated;
      reader.readMessage(value,bottle_account_v1_events_pb.OrganizationCreated.deserializeBinaryFromReader);
      msg.setOrganizationCreated(value);
      break;
    case 11:
      var value = new bottle_account_v1_events_pb.OrganizationJoined;
      reader.readMessage(value,bottle_account_v1_events_pb.OrganizationJoined.deserializeBinaryFromReader);
      msg.setOrganizationJoined(value);
      break;
    case 12:
      var value = new bottle_account_v1_events_pb.OrganizationLeft;
      reader.readMessage(value,bottle_account_v1_events_pb.OrganizationLeft.deserializeBinaryFromReader);
      msg.setOrganizationLeft(value);
      break;
    case 31:
      var value = new bottle_assembly_v1_events_pb.BuildCancelled;
      reader.readMessage(value,bottle_assembly_v1_events_pb.BuildCancelled.deserializeBinaryFromReader);
      msg.setBuildCancelled(value);
      break;
    case 13:
      var value = new bottle_assembly_v1_events_pb.BuildCreated;
      reader.readMessage(value,bottle_assembly_v1_events_pb.BuildCreated.deserializeBinaryFromReader);
      msg.setBuildCreated(value);
      break;
    case 14:
      var value = new bottle_assembly_v1_events_pb.BuildUpdated;
      reader.readMessage(value,bottle_assembly_v1_events_pb.BuildUpdated.deserializeBinaryFromReader);
      msg.setBuildUpdated(value);
      break;
    case 28:
      var value = new bottle_assembly_v1_events_pb.BuildPicked;
      reader.readMessage(value,bottle_assembly_v1_events_pb.BuildPicked.deserializeBinaryFromReader);
      msg.setBuildPicked(value);
      break;
    case 29:
      var value = new bottle_assembly_v1_events_pb.ComponentDemandUpdated;
      reader.readMessage(value,bottle_assembly_v1_events_pb.ComponentDemandUpdated.deserializeBinaryFromReader);
      msg.setComponentDemandUpdated(value);
      break;
    case 15:
      var value = new bottle_inventory_v1_events_pb.ComponentAvailabilityUpdated;
      reader.readMessage(value,bottle_inventory_v1_events_pb.ComponentAvailabilityUpdated.deserializeBinaryFromReader);
      msg.setComponentAvailabilityUpdated(value);
      break;
    case 30:
      var value = new bottle_inventory_v1_events_pb.SkuDetailsUpdated;
      reader.readMessage(value,bottle_inventory_v1_events_pb.SkuDetailsUpdated.deserializeBinaryFromReader);
      msg.setSkuDetailsUpdated(value);
      break;
    case 25:
      var value = new bottle_inventory_v1_events_pb.PartCreated;
      reader.readMessage(value,bottle_inventory_v1_events_pb.PartCreated.deserializeBinaryFromReader);
      msg.setPartCreated(value);
      break;
    case 26:
      var value = new bottle_inventory_v1_events_pb.PartUpdated;
      reader.readMessage(value,bottle_inventory_v1_events_pb.PartUpdated.deserializeBinaryFromReader);
      msg.setPartUpdated(value);
      break;
    case 32:
      var value = new bottle_inventory_v1_events_pb.ComponentKitChanged;
      reader.readMessage(value,bottle_inventory_v1_events_pb.ComponentKitChanged.deserializeBinaryFromReader);
      msg.setComponentKitChanged(value);
      break;
    case 16:
      var value = new bottle_support_v1_events_pb.QuestionCreated;
      reader.readMessage(value,bottle_support_v1_events_pb.QuestionCreated.deserializeBinaryFromReader);
      msg.setQuestionCreated(value);
      break;
    case 17:
      var value = new bottle_support_v1_events_pb.MacroApplied;
      reader.readMessage(value,bottle_support_v1_events_pb.MacroApplied.deserializeBinaryFromReader);
      msg.setMacroApplied(value);
      break;
    case 33:
      var value = new bottle_templates_v1_events_pb.TemplatedEmail;
      reader.readMessage(value,bottle_templates_v1_events_pb.TemplatedEmail.deserializeBinaryFromReader);
      msg.setTemplatedEmail(value);
      break;
    case 27:
      var value = new bottle_core_v1_testing_pb.TestEvent;
      reader.readMessage(value,bottle_core_v1_testing_pb.TestEvent.deserializeBinaryFromReader);
      msg.setTestEvent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.core.v1.Bottle.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.core.v1.Bottle.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.core.v1.Bottle} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.core.v1.Bottle.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getOrderCreated();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      bottle_fulfillment_v1_events_pb.OrderCreated.serializeBinaryToWriter
    );
  }
  f = message.getOrderUpdated();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      bottle_fulfillment_v1_events_pb.OrderUpdated.serializeBinaryToWriter
    );
  }
  f = message.getOrderVerificationRequest();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      bottle_fulfillment_v1_order_verification_service_pb.OrderVerificationRequest.serializeBinaryToWriter
    );
  }
  f = message.getOrderVerificationResponse();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      bottle_fulfillment_v1_order_verification_service_pb.OrderVerificationResponse.serializeBinaryToWriter
    );
  }
  f = message.getTribbleFailed();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      bottle_fulfillment_v1_events_pb.TribbleFailed.serializeBinaryToWriter
    );
  }
  f = message.getUserCreated();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      bottle_account_v1_events_pb.UserCreated.serializeBinaryToWriter
    );
  }
  f = message.getUserDeleted();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      bottle_account_v1_events_pb.UserDeleted.serializeBinaryToWriter
    );
  }
  f = message.getUserUpdated();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      bottle_account_v1_events_pb.UserUpdated.serializeBinaryToWriter
    );
  }
  f = message.getPasswordChanged();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      bottle_account_v1_events_pb.PasswordChanged.serializeBinaryToWriter
    );
  }
  f = message.getPasswordReset();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      bottle_account_v1_events_pb.PasswordReset.serializeBinaryToWriter
    );
  }
  f = message.getTwoFactorRequested();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      bottle_account_v1_events_pb.TwoFactorRequested.serializeBinaryToWriter
    );
  }
  f = message.getTwoFactorRecoveryCodeUsed();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      bottle_account_v1_events_pb.TwoFactorRecoveryCodeUsed.serializeBinaryToWriter
    );
  }
  f = message.getOrganizationCreated();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      bottle_account_v1_events_pb.OrganizationCreated.serializeBinaryToWriter
    );
  }
  f = message.getOrganizationJoined();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      bottle_account_v1_events_pb.OrganizationJoined.serializeBinaryToWriter
    );
  }
  f = message.getOrganizationLeft();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      bottle_account_v1_events_pb.OrganizationLeft.serializeBinaryToWriter
    );
  }
  f = message.getBuildCancelled();
  if (f != null) {
    writer.writeMessage(
      31,
      f,
      bottle_assembly_v1_events_pb.BuildCancelled.serializeBinaryToWriter
    );
  }
  f = message.getBuildCreated();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      bottle_assembly_v1_events_pb.BuildCreated.serializeBinaryToWriter
    );
  }
  f = message.getBuildUpdated();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      bottle_assembly_v1_events_pb.BuildUpdated.serializeBinaryToWriter
    );
  }
  f = message.getBuildPicked();
  if (f != null) {
    writer.writeMessage(
      28,
      f,
      bottle_assembly_v1_events_pb.BuildPicked.serializeBinaryToWriter
    );
  }
  f = message.getComponentDemandUpdated();
  if (f != null) {
    writer.writeMessage(
      29,
      f,
      bottle_assembly_v1_events_pb.ComponentDemandUpdated.serializeBinaryToWriter
    );
  }
  f = message.getComponentAvailabilityUpdated();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      bottle_inventory_v1_events_pb.ComponentAvailabilityUpdated.serializeBinaryToWriter
    );
  }
  f = message.getSkuDetailsUpdated();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      bottle_inventory_v1_events_pb.SkuDetailsUpdated.serializeBinaryToWriter
    );
  }
  f = message.getPartCreated();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      bottle_inventory_v1_events_pb.PartCreated.serializeBinaryToWriter
    );
  }
  f = message.getPartUpdated();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      bottle_inventory_v1_events_pb.PartUpdated.serializeBinaryToWriter
    );
  }
  f = message.getComponentKitChanged();
  if (f != null) {
    writer.writeMessage(
      32,
      f,
      bottle_inventory_v1_events_pb.ComponentKitChanged.serializeBinaryToWriter
    );
  }
  f = message.getQuestionCreated();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      bottle_support_v1_events_pb.QuestionCreated.serializeBinaryToWriter
    );
  }
  f = message.getMacroApplied();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      bottle_support_v1_events_pb.MacroApplied.serializeBinaryToWriter
    );
  }
  f = message.getTemplatedEmail();
  if (f != null) {
    writer.writeMessage(
      33,
      f,
      bottle_templates_v1_events_pb.TemplatedEmail.serializeBinaryToWriter
    );
  }
  f = message.getTestEvent();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      bottle_core_v1_testing_pb.TestEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 timestamp = 1;
 * @return {number}
 */
proto.bottle.core.v1.Bottle.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string request_id = 2;
 * @return {string}
 */
proto.bottle.core.v1.Bottle.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string source = 3;
 * @return {string}
 */
proto.bottle.core.v1.Bottle.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.setSource = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bottle.fulfillment.v1.OrderCreated order_created = 4;
 * @return {?proto.bottle.fulfillment.v1.OrderCreated}
 */
proto.bottle.core.v1.Bottle.prototype.getOrderCreated = function() {
  return /** @type{?proto.bottle.fulfillment.v1.OrderCreated} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_events_pb.OrderCreated, 4));
};


/**
 * @param {?proto.bottle.fulfillment.v1.OrderCreated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setOrderCreated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearOrderCreated = function() {
  return this.setOrderCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasOrderCreated = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bottle.fulfillment.v1.OrderUpdated order_updated = 22;
 * @return {?proto.bottle.fulfillment.v1.OrderUpdated}
 */
proto.bottle.core.v1.Bottle.prototype.getOrderUpdated = function() {
  return /** @type{?proto.bottle.fulfillment.v1.OrderUpdated} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_events_pb.OrderUpdated, 22));
};


/**
 * @param {?proto.bottle.fulfillment.v1.OrderUpdated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setOrderUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 22, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearOrderUpdated = function() {
  return this.setOrderUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasOrderUpdated = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional bottle.fulfillment.v1.OrderVerificationRequest order_verification_request = 23;
 * @return {?proto.bottle.fulfillment.v1.OrderVerificationRequest}
 */
proto.bottle.core.v1.Bottle.prototype.getOrderVerificationRequest = function() {
  return /** @type{?proto.bottle.fulfillment.v1.OrderVerificationRequest} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_order_verification_service_pb.OrderVerificationRequest, 23));
};


/**
 * @param {?proto.bottle.fulfillment.v1.OrderVerificationRequest|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setOrderVerificationRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 23, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearOrderVerificationRequest = function() {
  return this.setOrderVerificationRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasOrderVerificationRequest = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional bottle.fulfillment.v1.OrderVerificationResponse order_verification_response = 24;
 * @return {?proto.bottle.fulfillment.v1.OrderVerificationResponse}
 */
proto.bottle.core.v1.Bottle.prototype.getOrderVerificationResponse = function() {
  return /** @type{?proto.bottle.fulfillment.v1.OrderVerificationResponse} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_order_verification_service_pb.OrderVerificationResponse, 24));
};


/**
 * @param {?proto.bottle.fulfillment.v1.OrderVerificationResponse|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setOrderVerificationResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 24, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearOrderVerificationResponse = function() {
  return this.setOrderVerificationResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasOrderVerificationResponse = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional bottle.fulfillment.v1.TribbleFailed tribble_failed = 6;
 * @return {?proto.bottle.fulfillment.v1.TribbleFailed}
 */
proto.bottle.core.v1.Bottle.prototype.getTribbleFailed = function() {
  return /** @type{?proto.bottle.fulfillment.v1.TribbleFailed} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_events_pb.TribbleFailed, 6));
};


/**
 * @param {?proto.bottle.fulfillment.v1.TribbleFailed|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setTribbleFailed = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearTribbleFailed = function() {
  return this.setTribbleFailed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasTribbleFailed = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bottle.account.v1.UserCreated user_created = 7;
 * @return {?proto.bottle.account.v1.UserCreated}
 */
proto.bottle.core.v1.Bottle.prototype.getUserCreated = function() {
  return /** @type{?proto.bottle.account.v1.UserCreated} */ (
    jspb.Message.getWrapperField(this, bottle_account_v1_events_pb.UserCreated, 7));
};


/**
 * @param {?proto.bottle.account.v1.UserCreated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setUserCreated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearUserCreated = function() {
  return this.setUserCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasUserCreated = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bottle.account.v1.UserDeleted user_deleted = 20;
 * @return {?proto.bottle.account.v1.UserDeleted}
 */
proto.bottle.core.v1.Bottle.prototype.getUserDeleted = function() {
  return /** @type{?proto.bottle.account.v1.UserDeleted} */ (
    jspb.Message.getWrapperField(this, bottle_account_v1_events_pb.UserDeleted, 20));
};


/**
 * @param {?proto.bottle.account.v1.UserDeleted|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setUserDeleted = function(value) {
  return jspb.Message.setOneofWrapperField(this, 20, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearUserDeleted = function() {
  return this.setUserDeleted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasUserDeleted = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional bottle.account.v1.UserUpdated user_updated = 21;
 * @return {?proto.bottle.account.v1.UserUpdated}
 */
proto.bottle.core.v1.Bottle.prototype.getUserUpdated = function() {
  return /** @type{?proto.bottle.account.v1.UserUpdated} */ (
    jspb.Message.getWrapperField(this, bottle_account_v1_events_pb.UserUpdated, 21));
};


/**
 * @param {?proto.bottle.account.v1.UserUpdated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setUserUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 21, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearUserUpdated = function() {
  return this.setUserUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasUserUpdated = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional bottle.account.v1.PasswordChanged password_changed = 8;
 * @return {?proto.bottle.account.v1.PasswordChanged}
 */
proto.bottle.core.v1.Bottle.prototype.getPasswordChanged = function() {
  return /** @type{?proto.bottle.account.v1.PasswordChanged} */ (
    jspb.Message.getWrapperField(this, bottle_account_v1_events_pb.PasswordChanged, 8));
};


/**
 * @param {?proto.bottle.account.v1.PasswordChanged|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setPasswordChanged = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearPasswordChanged = function() {
  return this.setPasswordChanged(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasPasswordChanged = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bottle.account.v1.PasswordReset password_reset = 9;
 * @return {?proto.bottle.account.v1.PasswordReset}
 */
proto.bottle.core.v1.Bottle.prototype.getPasswordReset = function() {
  return /** @type{?proto.bottle.account.v1.PasswordReset} */ (
    jspb.Message.getWrapperField(this, bottle_account_v1_events_pb.PasswordReset, 9));
};


/**
 * @param {?proto.bottle.account.v1.PasswordReset|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setPasswordReset = function(value) {
  return jspb.Message.setOneofWrapperField(this, 9, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearPasswordReset = function() {
  return this.setPasswordReset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasPasswordReset = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional bottle.account.v1.TwoFactorRequested two_factor_requested = 18;
 * @return {?proto.bottle.account.v1.TwoFactorRequested}
 */
proto.bottle.core.v1.Bottle.prototype.getTwoFactorRequested = function() {
  return /** @type{?proto.bottle.account.v1.TwoFactorRequested} */ (
    jspb.Message.getWrapperField(this, bottle_account_v1_events_pb.TwoFactorRequested, 18));
};


/**
 * @param {?proto.bottle.account.v1.TwoFactorRequested|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setTwoFactorRequested = function(value) {
  return jspb.Message.setOneofWrapperField(this, 18, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearTwoFactorRequested = function() {
  return this.setTwoFactorRequested(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasTwoFactorRequested = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional bottle.account.v1.TwoFactorRecoveryCodeUsed two_factor_recovery_code_used = 19;
 * @return {?proto.bottle.account.v1.TwoFactorRecoveryCodeUsed}
 */
proto.bottle.core.v1.Bottle.prototype.getTwoFactorRecoveryCodeUsed = function() {
  return /** @type{?proto.bottle.account.v1.TwoFactorRecoveryCodeUsed} */ (
    jspb.Message.getWrapperField(this, bottle_account_v1_events_pb.TwoFactorRecoveryCodeUsed, 19));
};


/**
 * @param {?proto.bottle.account.v1.TwoFactorRecoveryCodeUsed|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setTwoFactorRecoveryCodeUsed = function(value) {
  return jspb.Message.setOneofWrapperField(this, 19, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearTwoFactorRecoveryCodeUsed = function() {
  return this.setTwoFactorRecoveryCodeUsed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasTwoFactorRecoveryCodeUsed = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional bottle.account.v1.OrganizationCreated organization_created = 10;
 * @return {?proto.bottle.account.v1.OrganizationCreated}
 */
proto.bottle.core.v1.Bottle.prototype.getOrganizationCreated = function() {
  return /** @type{?proto.bottle.account.v1.OrganizationCreated} */ (
    jspb.Message.getWrapperField(this, bottle_account_v1_events_pb.OrganizationCreated, 10));
};


/**
 * @param {?proto.bottle.account.v1.OrganizationCreated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setOrganizationCreated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearOrganizationCreated = function() {
  return this.setOrganizationCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasOrganizationCreated = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional bottle.account.v1.OrganizationJoined organization_joined = 11;
 * @return {?proto.bottle.account.v1.OrganizationJoined}
 */
proto.bottle.core.v1.Bottle.prototype.getOrganizationJoined = function() {
  return /** @type{?proto.bottle.account.v1.OrganizationJoined} */ (
    jspb.Message.getWrapperField(this, bottle_account_v1_events_pb.OrganizationJoined, 11));
};


/**
 * @param {?proto.bottle.account.v1.OrganizationJoined|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setOrganizationJoined = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearOrganizationJoined = function() {
  return this.setOrganizationJoined(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasOrganizationJoined = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional bottle.account.v1.OrganizationLeft organization_left = 12;
 * @return {?proto.bottle.account.v1.OrganizationLeft}
 */
proto.bottle.core.v1.Bottle.prototype.getOrganizationLeft = function() {
  return /** @type{?proto.bottle.account.v1.OrganizationLeft} */ (
    jspb.Message.getWrapperField(this, bottle_account_v1_events_pb.OrganizationLeft, 12));
};


/**
 * @param {?proto.bottle.account.v1.OrganizationLeft|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setOrganizationLeft = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearOrganizationLeft = function() {
  return this.setOrganizationLeft(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasOrganizationLeft = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional bottle.assembly.v1.BuildCancelled build_cancelled = 31;
 * @return {?proto.bottle.assembly.v1.BuildCancelled}
 */
proto.bottle.core.v1.Bottle.prototype.getBuildCancelled = function() {
  return /** @type{?proto.bottle.assembly.v1.BuildCancelled} */ (
    jspb.Message.getWrapperField(this, bottle_assembly_v1_events_pb.BuildCancelled, 31));
};


/**
 * @param {?proto.bottle.assembly.v1.BuildCancelled|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setBuildCancelled = function(value) {
  return jspb.Message.setOneofWrapperField(this, 31, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearBuildCancelled = function() {
  return this.setBuildCancelled(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasBuildCancelled = function() {
  return jspb.Message.getField(this, 31) != null;
};


/**
 * optional bottle.assembly.v1.BuildCreated build_created = 13;
 * @return {?proto.bottle.assembly.v1.BuildCreated}
 */
proto.bottle.core.v1.Bottle.prototype.getBuildCreated = function() {
  return /** @type{?proto.bottle.assembly.v1.BuildCreated} */ (
    jspb.Message.getWrapperField(this, bottle_assembly_v1_events_pb.BuildCreated, 13));
};


/**
 * @param {?proto.bottle.assembly.v1.BuildCreated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setBuildCreated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 13, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearBuildCreated = function() {
  return this.setBuildCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasBuildCreated = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bottle.assembly.v1.BuildUpdated build_updated = 14;
 * @return {?proto.bottle.assembly.v1.BuildUpdated}
 */
proto.bottle.core.v1.Bottle.prototype.getBuildUpdated = function() {
  return /** @type{?proto.bottle.assembly.v1.BuildUpdated} */ (
    jspb.Message.getWrapperField(this, bottle_assembly_v1_events_pb.BuildUpdated, 14));
};


/**
 * @param {?proto.bottle.assembly.v1.BuildUpdated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setBuildUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 14, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearBuildUpdated = function() {
  return this.setBuildUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasBuildUpdated = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional bottle.assembly.v1.BuildPicked build_picked = 28;
 * @return {?proto.bottle.assembly.v1.BuildPicked}
 */
proto.bottle.core.v1.Bottle.prototype.getBuildPicked = function() {
  return /** @type{?proto.bottle.assembly.v1.BuildPicked} */ (
    jspb.Message.getWrapperField(this, bottle_assembly_v1_events_pb.BuildPicked, 28));
};


/**
 * @param {?proto.bottle.assembly.v1.BuildPicked|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setBuildPicked = function(value) {
  return jspb.Message.setOneofWrapperField(this, 28, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearBuildPicked = function() {
  return this.setBuildPicked(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasBuildPicked = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional bottle.assembly.v1.ComponentDemandUpdated component_demand_updated = 29;
 * @return {?proto.bottle.assembly.v1.ComponentDemandUpdated}
 */
proto.bottle.core.v1.Bottle.prototype.getComponentDemandUpdated = function() {
  return /** @type{?proto.bottle.assembly.v1.ComponentDemandUpdated} */ (
    jspb.Message.getWrapperField(this, bottle_assembly_v1_events_pb.ComponentDemandUpdated, 29));
};


/**
 * @param {?proto.bottle.assembly.v1.ComponentDemandUpdated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setComponentDemandUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 29, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearComponentDemandUpdated = function() {
  return this.setComponentDemandUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasComponentDemandUpdated = function() {
  return jspb.Message.getField(this, 29) != null;
};


/**
 * optional bottle.inventory.v1.ComponentAvailabilityUpdated component_availability_updated = 15;
 * @return {?proto.bottle.inventory.v1.ComponentAvailabilityUpdated}
 */
proto.bottle.core.v1.Bottle.prototype.getComponentAvailabilityUpdated = function() {
  return /** @type{?proto.bottle.inventory.v1.ComponentAvailabilityUpdated} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_events_pb.ComponentAvailabilityUpdated, 15));
};


/**
 * @param {?proto.bottle.inventory.v1.ComponentAvailabilityUpdated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setComponentAvailabilityUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 15, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearComponentAvailabilityUpdated = function() {
  return this.setComponentAvailabilityUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasComponentAvailabilityUpdated = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional bottle.inventory.v1.SkuDetailsUpdated sku_details_updated = 30;
 * @return {?proto.bottle.inventory.v1.SkuDetailsUpdated}
 */
proto.bottle.core.v1.Bottle.prototype.getSkuDetailsUpdated = function() {
  return /** @type{?proto.bottle.inventory.v1.SkuDetailsUpdated} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_events_pb.SkuDetailsUpdated, 30));
};


/**
 * @param {?proto.bottle.inventory.v1.SkuDetailsUpdated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setSkuDetailsUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 30, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearSkuDetailsUpdated = function() {
  return this.setSkuDetailsUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasSkuDetailsUpdated = function() {
  return jspb.Message.getField(this, 30) != null;
};


/**
 * optional bottle.inventory.v1.PartCreated part_created = 25;
 * @return {?proto.bottle.inventory.v1.PartCreated}
 */
proto.bottle.core.v1.Bottle.prototype.getPartCreated = function() {
  return /** @type{?proto.bottle.inventory.v1.PartCreated} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_events_pb.PartCreated, 25));
};


/**
 * @param {?proto.bottle.inventory.v1.PartCreated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setPartCreated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 25, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearPartCreated = function() {
  return this.setPartCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasPartCreated = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional bottle.inventory.v1.PartUpdated part_updated = 26;
 * @return {?proto.bottle.inventory.v1.PartUpdated}
 */
proto.bottle.core.v1.Bottle.prototype.getPartUpdated = function() {
  return /** @type{?proto.bottle.inventory.v1.PartUpdated} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_events_pb.PartUpdated, 26));
};


/**
 * @param {?proto.bottle.inventory.v1.PartUpdated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setPartUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 26, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearPartUpdated = function() {
  return this.setPartUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasPartUpdated = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional bottle.inventory.v1.ComponentKitChanged component_kit_changed = 32;
 * @return {?proto.bottle.inventory.v1.ComponentKitChanged}
 */
proto.bottle.core.v1.Bottle.prototype.getComponentKitChanged = function() {
  return /** @type{?proto.bottle.inventory.v1.ComponentKitChanged} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_events_pb.ComponentKitChanged, 32));
};


/**
 * @param {?proto.bottle.inventory.v1.ComponentKitChanged|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setComponentKitChanged = function(value) {
  return jspb.Message.setOneofWrapperField(this, 32, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearComponentKitChanged = function() {
  return this.setComponentKitChanged(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasComponentKitChanged = function() {
  return jspb.Message.getField(this, 32) != null;
};


/**
 * optional bottle.support.v1.QuestionCreated question_created = 16;
 * @return {?proto.bottle.support.v1.QuestionCreated}
 */
proto.bottle.core.v1.Bottle.prototype.getQuestionCreated = function() {
  return /** @type{?proto.bottle.support.v1.QuestionCreated} */ (
    jspb.Message.getWrapperField(this, bottle_support_v1_events_pb.QuestionCreated, 16));
};


/**
 * @param {?proto.bottle.support.v1.QuestionCreated|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setQuestionCreated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 16, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearQuestionCreated = function() {
  return this.setQuestionCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasQuestionCreated = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional bottle.support.v1.MacroApplied macro_applied = 17;
 * @return {?proto.bottle.support.v1.MacroApplied}
 */
proto.bottle.core.v1.Bottle.prototype.getMacroApplied = function() {
  return /** @type{?proto.bottle.support.v1.MacroApplied} */ (
    jspb.Message.getWrapperField(this, bottle_support_v1_events_pb.MacroApplied, 17));
};


/**
 * @param {?proto.bottle.support.v1.MacroApplied|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setMacroApplied = function(value) {
  return jspb.Message.setOneofWrapperField(this, 17, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearMacroApplied = function() {
  return this.setMacroApplied(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasMacroApplied = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional bottle.templates.v1.TemplatedEmail templated_email = 33;
 * @return {?proto.bottle.templates.v1.TemplatedEmail}
 */
proto.bottle.core.v1.Bottle.prototype.getTemplatedEmail = function() {
  return /** @type{?proto.bottle.templates.v1.TemplatedEmail} */ (
    jspb.Message.getWrapperField(this, bottle_templates_v1_events_pb.TemplatedEmail, 33));
};


/**
 * @param {?proto.bottle.templates.v1.TemplatedEmail|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setTemplatedEmail = function(value) {
  return jspb.Message.setOneofWrapperField(this, 33, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearTemplatedEmail = function() {
  return this.setTemplatedEmail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasTemplatedEmail = function() {
  return jspb.Message.getField(this, 33) != null;
};


/**
 * optional TestEvent test_event = 27;
 * @return {?proto.bottle.core.v1.TestEvent}
 */
proto.bottle.core.v1.Bottle.prototype.getTestEvent = function() {
  return /** @type{?proto.bottle.core.v1.TestEvent} */ (
    jspb.Message.getWrapperField(this, bottle_core_v1_testing_pb.TestEvent, 27));
};


/**
 * @param {?proto.bottle.core.v1.TestEvent|undefined} value
 * @return {!proto.bottle.core.v1.Bottle} returns this
*/
proto.bottle.core.v1.Bottle.prototype.setTestEvent = function(value) {
  return jspb.Message.setOneofWrapperField(this, 27, proto.bottle.core.v1.Bottle.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.core.v1.Bottle} returns this
 */
proto.bottle.core.v1.Bottle.prototype.clearTestEvent = function() {
  return this.setTestEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.core.v1.Bottle.prototype.hasTestEvent = function() {
  return jspb.Message.getField(this, 27) != null;
};


goog.object.extend(exports, proto.bottle.core.v1);
