// source: bottle/templates/v1/events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var bottle_templates_v1_typed_attachment_pb = require('../../../bottle/templates/v1/typed_attachment_pb.js');
goog.object.extend(proto, bottle_templates_v1_typed_attachment_pb);
goog.exportSymbol('proto.bottle.templates.v1.TemplatedEmail', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.templates.v1.TemplatedEmail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bottle.templates.v1.TemplatedEmail.repeatedFields_, null);
};
goog.inherits(proto.bottle.templates.v1.TemplatedEmail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.templates.v1.TemplatedEmail.displayName = 'proto.bottle.templates.v1.TemplatedEmail';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bottle.templates.v1.TemplatedEmail.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.templates.v1.TemplatedEmail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.templates.v1.TemplatedEmail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.templates.v1.TemplatedEmail.toObject = function(includeInstance, msg) {
  var f, obj = {
    templateName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    formVariablesMap: (f = msg.getFormVariablesMap()) ? f.toObject(includeInstance, undefined) : [],
    emailFrom: jspb.Message.getFieldWithDefault(msg, 3, ""),
    emailTo: jspb.Message.getFieldWithDefault(msg, 4, ""),
    subject: jspb.Message.getFieldWithDefault(msg, 5, ""),
    attachmentsList: jspb.Message.toObjectList(msg.getAttachmentsList(),
    bottle_templates_v1_typed_attachment_pb.TypedAttachment.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.templates.v1.TemplatedEmail}
 */
proto.bottle.templates.v1.TemplatedEmail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.templates.v1.TemplatedEmail;
  return proto.bottle.templates.v1.TemplatedEmail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.templates.v1.TemplatedEmail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.templates.v1.TemplatedEmail}
 */
proto.bottle.templates.v1.TemplatedEmail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTemplateName(value);
      break;
    case 2:
      var value = msg.getFormVariablesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmailFrom(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmailTo(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 6:
      var value = new bottle_templates_v1_typed_attachment_pb.TypedAttachment;
      reader.readMessage(value,bottle_templates_v1_typed_attachment_pb.TypedAttachment.deserializeBinaryFromReader);
      msg.addAttachments(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.templates.v1.TemplatedEmail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.templates.v1.TemplatedEmail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.templates.v1.TemplatedEmail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTemplateName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFormVariablesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getEmailFrom();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEmailTo();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSubject();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAttachmentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      bottle_templates_v1_typed_attachment_pb.TypedAttachment.serializeBinaryToWriter
    );
  }
};


/**
 * optional string template_name = 1;
 * @return {string}
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.getTemplateName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.templates.v1.TemplatedEmail} returns this
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.setTemplateName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<string, string> form_variables = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.getFormVariablesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.bottle.templates.v1.TemplatedEmail} returns this
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.clearFormVariablesMap = function() {
  this.getFormVariablesMap().clear();
  return this;};


/**
 * optional string email_from = 3;
 * @return {string}
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.getEmailFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.templates.v1.TemplatedEmail} returns this
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.setEmailFrom = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string email_to = 4;
 * @return {string}
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.getEmailTo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.templates.v1.TemplatedEmail} returns this
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.setEmailTo = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string subject = 5;
 * @return {string}
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.templates.v1.TemplatedEmail} returns this
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.setSubject = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated TypedAttachment attachments = 6;
 * @return {!Array<!proto.bottle.templates.v1.TypedAttachment>}
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.getAttachmentsList = function() {
  return /** @type{!Array<!proto.bottle.templates.v1.TypedAttachment>} */ (
    jspb.Message.getRepeatedWrapperField(this, bottle_templates_v1_typed_attachment_pb.TypedAttachment, 6));
};


/**
 * @param {!Array<!proto.bottle.templates.v1.TypedAttachment>} value
 * @return {!proto.bottle.templates.v1.TemplatedEmail} returns this
*/
proto.bottle.templates.v1.TemplatedEmail.prototype.setAttachmentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.bottle.templates.v1.TypedAttachment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bottle.templates.v1.TypedAttachment}
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.addAttachments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.bottle.templates.v1.TypedAttachment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bottle.templates.v1.TemplatedEmail} returns this
 */
proto.bottle.templates.v1.TemplatedEmail.prototype.clearAttachmentsList = function() {
  return this.setAttachmentsList([]);
};


goog.object.extend(exports, proto.bottle.templates.v1);
