// source: bottle/fulfillment/v1/events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var bottle_fulfillment_v1_order_pb = require('../../../bottle/fulfillment/v1/order_pb.js');
goog.object.extend(proto, bottle_fulfillment_v1_order_pb);
goog.exportSymbol('proto.bottle.fulfillment.v1.OrderCreated', null, global);
goog.exportSymbol('proto.bottle.fulfillment.v1.OrderUpdated', null, global);
goog.exportSymbol('proto.bottle.fulfillment.v1.TribbleFailed', null, global);
goog.exportSymbol('proto.bottle.fulfillment.v1.TribbleFailed.FailureType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.fulfillment.v1.OrderCreated = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.fulfillment.v1.OrderCreated, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.fulfillment.v1.OrderCreated.displayName = 'proto.bottle.fulfillment.v1.OrderCreated';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.fulfillment.v1.OrderUpdated = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.fulfillment.v1.OrderUpdated, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.fulfillment.v1.OrderUpdated.displayName = 'proto.bottle.fulfillment.v1.OrderUpdated';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.fulfillment.v1.TribbleFailed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.fulfillment.v1.TribbleFailed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.fulfillment.v1.TribbleFailed.displayName = 'proto.bottle.fulfillment.v1.TribbleFailed';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.fulfillment.v1.OrderCreated.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.fulfillment.v1.OrderCreated.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.fulfillment.v1.OrderCreated} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.fulfillment.v1.OrderCreated.toObject = function(includeInstance, msg) {
  var f, obj = {
    order: (f = msg.getOrder()) && bottle_fulfillment_v1_order_pb.Order.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.fulfillment.v1.OrderCreated}
 */
proto.bottle.fulfillment.v1.OrderCreated.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.fulfillment.v1.OrderCreated;
  return proto.bottle.fulfillment.v1.OrderCreated.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.fulfillment.v1.OrderCreated} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.fulfillment.v1.OrderCreated}
 */
proto.bottle.fulfillment.v1.OrderCreated.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bottle_fulfillment_v1_order_pb.Order;
      reader.readMessage(value,bottle_fulfillment_v1_order_pb.Order.deserializeBinaryFromReader);
      msg.setOrder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.fulfillment.v1.OrderCreated.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.fulfillment.v1.OrderCreated.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.fulfillment.v1.OrderCreated} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.fulfillment.v1.OrderCreated.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrder();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bottle_fulfillment_v1_order_pb.Order.serializeBinaryToWriter
    );
  }
};


/**
 * optional Order order = 1;
 * @return {?proto.bottle.fulfillment.v1.Order}
 */
proto.bottle.fulfillment.v1.OrderCreated.prototype.getOrder = function() {
  return /** @type{?proto.bottle.fulfillment.v1.Order} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_order_pb.Order, 1));
};


/**
 * @param {?proto.bottle.fulfillment.v1.Order|undefined} value
 * @return {!proto.bottle.fulfillment.v1.OrderCreated} returns this
*/
proto.bottle.fulfillment.v1.OrderCreated.prototype.setOrder = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.fulfillment.v1.OrderCreated} returns this
 */
proto.bottle.fulfillment.v1.OrderCreated.prototype.clearOrder = function() {
  return this.setOrder(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.fulfillment.v1.OrderCreated.prototype.hasOrder = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.fulfillment.v1.OrderUpdated.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.fulfillment.v1.OrderUpdated.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.fulfillment.v1.OrderUpdated} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.fulfillment.v1.OrderUpdated.toObject = function(includeInstance, msg) {
  var f, obj = {
    old: (f = msg.getOld()) && bottle_fulfillment_v1_order_pb.Order.toObject(includeInstance, f),
    pb_new: (f = msg.getNew()) && bottle_fulfillment_v1_order_pb.Order.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.fulfillment.v1.OrderUpdated}
 */
proto.bottle.fulfillment.v1.OrderUpdated.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.fulfillment.v1.OrderUpdated;
  return proto.bottle.fulfillment.v1.OrderUpdated.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.fulfillment.v1.OrderUpdated} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.fulfillment.v1.OrderUpdated}
 */
proto.bottle.fulfillment.v1.OrderUpdated.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bottle_fulfillment_v1_order_pb.Order;
      reader.readMessage(value,bottle_fulfillment_v1_order_pb.Order.deserializeBinaryFromReader);
      msg.setOld(value);
      break;
    case 2:
      var value = new bottle_fulfillment_v1_order_pb.Order;
      reader.readMessage(value,bottle_fulfillment_v1_order_pb.Order.deserializeBinaryFromReader);
      msg.setNew(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.fulfillment.v1.OrderUpdated.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.fulfillment.v1.OrderUpdated.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.fulfillment.v1.OrderUpdated} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.fulfillment.v1.OrderUpdated.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOld();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bottle_fulfillment_v1_order_pb.Order.serializeBinaryToWriter
    );
  }
  f = message.getNew();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      bottle_fulfillment_v1_order_pb.Order.serializeBinaryToWriter
    );
  }
};


/**
 * optional Order old = 1;
 * @return {?proto.bottle.fulfillment.v1.Order}
 */
proto.bottle.fulfillment.v1.OrderUpdated.prototype.getOld = function() {
  return /** @type{?proto.bottle.fulfillment.v1.Order} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_order_pb.Order, 1));
};


/**
 * @param {?proto.bottle.fulfillment.v1.Order|undefined} value
 * @return {!proto.bottle.fulfillment.v1.OrderUpdated} returns this
*/
proto.bottle.fulfillment.v1.OrderUpdated.prototype.setOld = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.fulfillment.v1.OrderUpdated} returns this
 */
proto.bottle.fulfillment.v1.OrderUpdated.prototype.clearOld = function() {
  return this.setOld(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.fulfillment.v1.OrderUpdated.prototype.hasOld = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Order new = 2;
 * @return {?proto.bottle.fulfillment.v1.Order}
 */
proto.bottle.fulfillment.v1.OrderUpdated.prototype.getNew = function() {
  return /** @type{?proto.bottle.fulfillment.v1.Order} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_order_pb.Order, 2));
};


/**
 * @param {?proto.bottle.fulfillment.v1.Order|undefined} value
 * @return {!proto.bottle.fulfillment.v1.OrderUpdated} returns this
*/
proto.bottle.fulfillment.v1.OrderUpdated.prototype.setNew = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.fulfillment.v1.OrderUpdated} returns this
 */
proto.bottle.fulfillment.v1.OrderUpdated.prototype.clearNew = function() {
  return this.setNew(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.fulfillment.v1.OrderUpdated.prototype.hasNew = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.fulfillment.v1.TribbleFailed.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.fulfillment.v1.TribbleFailed.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.fulfillment.v1.TribbleFailed} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.fulfillment.v1.TribbleFailed.toObject = function(includeInstance, msg) {
  var f, obj = {
    order: (f = msg.getOrder()) && bottle_fulfillment_v1_order_pb.Order.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.fulfillment.v1.TribbleFailed}
 */
proto.bottle.fulfillment.v1.TribbleFailed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.fulfillment.v1.TribbleFailed;
  return proto.bottle.fulfillment.v1.TribbleFailed.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.fulfillment.v1.TribbleFailed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.fulfillment.v1.TribbleFailed}
 */
proto.bottle.fulfillment.v1.TribbleFailed.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bottle_fulfillment_v1_order_pb.Order;
      reader.readMessage(value,bottle_fulfillment_v1_order_pb.Order.deserializeBinaryFromReader);
      msg.setOrder(value);
      break;
    case 2:
      var value = /** @type {!proto.bottle.fulfillment.v1.TribbleFailed.FailureType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.fulfillment.v1.TribbleFailed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.fulfillment.v1.TribbleFailed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.fulfillment.v1.TribbleFailed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.fulfillment.v1.TribbleFailed.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrder();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bottle_fulfillment_v1_order_pb.Order.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.bottle.fulfillment.v1.TribbleFailed.FailureType = {
  FAILURE_TYPE_UNSPECIFIED: 0,
  FAILURE_TYPE_INVALID_ADDRESS: 1,
  FAILURE_TYPE_ALREADY_SHIPPED: 2,
  FAILURE_TYPE_TRIBBLE_ERROR: 3
};

/**
 * optional Order order = 1;
 * @return {?proto.bottle.fulfillment.v1.Order}
 */
proto.bottle.fulfillment.v1.TribbleFailed.prototype.getOrder = function() {
  return /** @type{?proto.bottle.fulfillment.v1.Order} */ (
    jspb.Message.getWrapperField(this, bottle_fulfillment_v1_order_pb.Order, 1));
};


/**
 * @param {?proto.bottle.fulfillment.v1.Order|undefined} value
 * @return {!proto.bottle.fulfillment.v1.TribbleFailed} returns this
*/
proto.bottle.fulfillment.v1.TribbleFailed.prototype.setOrder = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.fulfillment.v1.TribbleFailed} returns this
 */
proto.bottle.fulfillment.v1.TribbleFailed.prototype.clearOrder = function() {
  return this.setOrder(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.fulfillment.v1.TribbleFailed.prototype.hasOrder = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional FailureType type = 2;
 * @return {!proto.bottle.fulfillment.v1.TribbleFailed.FailureType}
 */
proto.bottle.fulfillment.v1.TribbleFailed.prototype.getType = function() {
  return /** @type {!proto.bottle.fulfillment.v1.TribbleFailed.FailureType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.bottle.fulfillment.v1.TribbleFailed.FailureType} value
 * @return {!proto.bottle.fulfillment.v1.TribbleFailed} returns this
 */
proto.bottle.fulfillment.v1.TribbleFailed.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


goog.object.extend(exports, proto.bottle.fulfillment.v1);
