// source: bottle/inventory/v1/part.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var bottle_inventory_v1_location_pb = require('../../../bottle/inventory/v1/location_pb.js');
goog.object.extend(proto, bottle_inventory_v1_location_pb);
var bottle_inventory_v1_sku_pb = require('../../../bottle/inventory/v1/sku_pb.js');
goog.object.extend(proto, bottle_inventory_v1_sku_pb);
goog.exportSymbol('proto.bottle.inventory.v1.Part', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.inventory.v1.Part = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.inventory.v1.Part, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.inventory.v1.Part.displayName = 'proto.bottle.inventory.v1.Part';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.inventory.v1.Part.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.inventory.v1.Part.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.inventory.v1.Part} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.Part.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    serialNumber: jspb.Message.getFieldWithDefault(msg, 2, ""),
    sku: (f = msg.getSku()) && bottle_inventory_v1_sku_pb.Sku.toObject(includeInstance, f),
    location: (f = msg.getLocation()) && bottle_inventory_v1_location_pb.Location.toObject(includeInstance, f),
    rmaDescription: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.inventory.v1.Part}
 */
proto.bottle.inventory.v1.Part.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.inventory.v1.Part;
  return proto.bottle.inventory.v1.Part.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.inventory.v1.Part} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.inventory.v1.Part}
 */
proto.bottle.inventory.v1.Part.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSerialNumber(value);
      break;
    case 3:
      var value = new bottle_inventory_v1_sku_pb.Sku;
      reader.readMessage(value,bottle_inventory_v1_sku_pb.Sku.deserializeBinaryFromReader);
      msg.setSku(value);
      break;
    case 4:
      var value = new bottle_inventory_v1_location_pb.Location;
      reader.readMessage(value,bottle_inventory_v1_location_pb.Location.deserializeBinaryFromReader);
      msg.setLocation(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRmaDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.inventory.v1.Part.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.inventory.v1.Part.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.inventory.v1.Part} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.Part.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSerialNumber();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSku();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      bottle_inventory_v1_sku_pb.Sku.serializeBinaryToWriter
    );
  }
  f = message.getLocation();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      bottle_inventory_v1_location_pb.Location.serializeBinaryToWriter
    );
  }
  f = message.getRmaDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.bottle.inventory.v1.Part.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.inventory.v1.Part} returns this
 */
proto.bottle.inventory.v1.Part.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string serial_number = 2;
 * @return {string}
 */
proto.bottle.inventory.v1.Part.prototype.getSerialNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.inventory.v1.Part} returns this
 */
proto.bottle.inventory.v1.Part.prototype.setSerialNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Sku sku = 3;
 * @return {?proto.bottle.inventory.v1.Sku}
 */
proto.bottle.inventory.v1.Part.prototype.getSku = function() {
  return /** @type{?proto.bottle.inventory.v1.Sku} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_sku_pb.Sku, 3));
};


/**
 * @param {?proto.bottle.inventory.v1.Sku|undefined} value
 * @return {!proto.bottle.inventory.v1.Part} returns this
*/
proto.bottle.inventory.v1.Part.prototype.setSku = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.inventory.v1.Part} returns this
 */
proto.bottle.inventory.v1.Part.prototype.clearSku = function() {
  return this.setSku(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.inventory.v1.Part.prototype.hasSku = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Location location = 4;
 * @return {?proto.bottle.inventory.v1.Location}
 */
proto.bottle.inventory.v1.Part.prototype.getLocation = function() {
  return /** @type{?proto.bottle.inventory.v1.Location} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_location_pb.Location, 4));
};


/**
 * @param {?proto.bottle.inventory.v1.Location|undefined} value
 * @return {!proto.bottle.inventory.v1.Part} returns this
*/
proto.bottle.inventory.v1.Part.prototype.setLocation = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.inventory.v1.Part} returns this
 */
proto.bottle.inventory.v1.Part.prototype.clearLocation = function() {
  return this.setLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.inventory.v1.Part.prototype.hasLocation = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string rma_description = 5;
 * @return {string}
 */
proto.bottle.inventory.v1.Part.prototype.getRmaDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.inventory.v1.Part} returns this
 */
proto.bottle.inventory.v1.Part.prototype.setRmaDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.bottle.inventory.v1);
