// source: bottle/support/v1/events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var bottle_support_v1_question_pb = require('../../../bottle/support/v1/question_pb.js');
goog.object.extend(proto, bottle_support_v1_question_pb);
goog.exportSymbol('proto.bottle.support.v1.MacroApplied', null, global);
goog.exportSymbol('proto.bottle.support.v1.QuestionCreated', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.support.v1.QuestionCreated = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.support.v1.QuestionCreated, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.support.v1.QuestionCreated.displayName = 'proto.bottle.support.v1.QuestionCreated';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.support.v1.MacroApplied = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bottle.support.v1.MacroApplied.repeatedFields_, null);
};
goog.inherits(proto.bottle.support.v1.MacroApplied, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.support.v1.MacroApplied.displayName = 'proto.bottle.support.v1.MacroApplied';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.support.v1.QuestionCreated.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.support.v1.QuestionCreated.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.support.v1.QuestionCreated} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.support.v1.QuestionCreated.toObject = function(includeInstance, msg) {
  var f, obj = {
    question: (f = msg.getQuestion()) && bottle_support_v1_question_pb.Question.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.support.v1.QuestionCreated}
 */
proto.bottle.support.v1.QuestionCreated.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.support.v1.QuestionCreated;
  return proto.bottle.support.v1.QuestionCreated.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.support.v1.QuestionCreated} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.support.v1.QuestionCreated}
 */
proto.bottle.support.v1.QuestionCreated.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bottle_support_v1_question_pb.Question;
      reader.readMessage(value,bottle_support_v1_question_pb.Question.deserializeBinaryFromReader);
      msg.setQuestion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.support.v1.QuestionCreated.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.support.v1.QuestionCreated.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.support.v1.QuestionCreated} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.support.v1.QuestionCreated.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuestion();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bottle_support_v1_question_pb.Question.serializeBinaryToWriter
    );
  }
};


/**
 * optional Question question = 1;
 * @return {?proto.bottle.support.v1.Question}
 */
proto.bottle.support.v1.QuestionCreated.prototype.getQuestion = function() {
  return /** @type{?proto.bottle.support.v1.Question} */ (
    jspb.Message.getWrapperField(this, bottle_support_v1_question_pb.Question, 1));
};


/**
 * @param {?proto.bottle.support.v1.Question|undefined} value
 * @return {!proto.bottle.support.v1.QuestionCreated} returns this
*/
proto.bottle.support.v1.QuestionCreated.prototype.setQuestion = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.support.v1.QuestionCreated} returns this
 */
proto.bottle.support.v1.QuestionCreated.prototype.clearQuestion = function() {
  return this.setQuestion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.support.v1.QuestionCreated.prototype.hasQuestion = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bottle.support.v1.MacroApplied.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.support.v1.MacroApplied.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.support.v1.MacroApplied.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.support.v1.MacroApplied} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.support.v1.MacroApplied.toObject = function(includeInstance, msg) {
  var f, obj = {
    question: (f = msg.getQuestion()) && bottle_support_v1_question_pb.Question.toObject(includeInstance, f),
    macrosList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.support.v1.MacroApplied}
 */
proto.bottle.support.v1.MacroApplied.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.support.v1.MacroApplied;
  return proto.bottle.support.v1.MacroApplied.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.support.v1.MacroApplied} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.support.v1.MacroApplied}
 */
proto.bottle.support.v1.MacroApplied.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new bottle_support_v1_question_pb.Question;
      reader.readMessage(value,bottle_support_v1_question_pb.Question.deserializeBinaryFromReader);
      msg.setQuestion(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addMacros(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.support.v1.MacroApplied.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.support.v1.MacroApplied.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.support.v1.MacroApplied} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.support.v1.MacroApplied.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuestion();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      bottle_support_v1_question_pb.Question.serializeBinaryToWriter
    );
  }
  f = message.getMacrosList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional Question question = 1;
 * @return {?proto.bottle.support.v1.Question}
 */
proto.bottle.support.v1.MacroApplied.prototype.getQuestion = function() {
  return /** @type{?proto.bottle.support.v1.Question} */ (
    jspb.Message.getWrapperField(this, bottle_support_v1_question_pb.Question, 1));
};


/**
 * @param {?proto.bottle.support.v1.Question|undefined} value
 * @return {!proto.bottle.support.v1.MacroApplied} returns this
*/
proto.bottle.support.v1.MacroApplied.prototype.setQuestion = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.support.v1.MacroApplied} returns this
 */
proto.bottle.support.v1.MacroApplied.prototype.clearQuestion = function() {
  return this.setQuestion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.support.v1.MacroApplied.prototype.hasQuestion = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string macros = 2;
 * @return {!Array<string>}
 */
proto.bottle.support.v1.MacroApplied.prototype.getMacrosList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.bottle.support.v1.MacroApplied} returns this
 */
proto.bottle.support.v1.MacroApplied.prototype.setMacrosList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.bottle.support.v1.MacroApplied} returns this
 */
proto.bottle.support.v1.MacroApplied.prototype.addMacros = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bottle.support.v1.MacroApplied} returns this
 */
proto.bottle.support.v1.MacroApplied.prototype.clearMacrosList = function() {
  return this.setMacrosList([]);
};


goog.object.extend(exports, proto.bottle.support.v1);
