// source: bottle/inventory/v1/service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var bottle_inventory_v1_component_pb = require('../../../bottle/inventory/v1/component_pb.js');
goog.object.extend(proto, bottle_inventory_v1_component_pb);
var bottle_inventory_v1_location_pb = require('../../../bottle/inventory/v1/location_pb.js');
goog.object.extend(proto, bottle_inventory_v1_location_pb);
goog.exportSymbol('proto.bottle.inventory.v1.ComponentAvailabilityListRequest', null, global);
goog.exportSymbol('proto.bottle.inventory.v1.ComponentAvailabilityListResponse', null, global);
goog.exportSymbol('proto.bottle.inventory.v1.LocationListRequest', null, global);
goog.exportSymbol('proto.bottle.inventory.v1.LocationListResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bottle.inventory.v1.ComponentAvailabilityListRequest.repeatedFields_, null);
};
goog.inherits(proto.bottle.inventory.v1.ComponentAvailabilityListRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.inventory.v1.ComponentAvailabilityListRequest.displayName = 'proto.bottle.inventory.v1.ComponentAvailabilityListRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.inventory.v1.ComponentAvailabilityListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.inventory.v1.ComponentAvailabilityListResponse.displayName = 'proto.bottle.inventory.v1.ComponentAvailabilityListResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.inventory.v1.LocationListRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bottle.inventory.v1.LocationListRequest.repeatedFields_, null);
};
goog.inherits(proto.bottle.inventory.v1.LocationListRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.inventory.v1.LocationListRequest.displayName = 'proto.bottle.inventory.v1.LocationListRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.inventory.v1.LocationListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.inventory.v1.LocationListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.inventory.v1.LocationListResponse.displayName = 'proto.bottle.inventory.v1.LocationListResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.inventory.v1.ComponentAvailabilityListRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.inventory.v1.ComponentAvailabilityListRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    componentsList: jspb.Message.toObjectList(msg.getComponentsList(),
    bottle_inventory_v1_component_pb.Component.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListRequest}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.inventory.v1.ComponentAvailabilityListRequest;
  return proto.bottle.inventory.v1.ComponentAvailabilityListRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.inventory.v1.ComponentAvailabilityListRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListRequest}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = new bottle_inventory_v1_component_pb.Component;
      reader.readMessage(value,bottle_inventory_v1_component_pb.Component.deserializeBinaryFromReader);
      msg.addComponents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.inventory.v1.ComponentAvailabilityListRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.inventory.v1.ComponentAvailabilityListRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getComponentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      bottle_inventory_v1_component_pb.Component.serializeBinaryToWriter
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListRequest} returns this
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Component components = 2;
 * @return {!Array<!proto.bottle.inventory.v1.Component>}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.prototype.getComponentsList = function() {
  return /** @type{!Array<!proto.bottle.inventory.v1.Component>} */ (
    jspb.Message.getRepeatedWrapperField(this, bottle_inventory_v1_component_pb.Component, 2));
};


/**
 * @param {!Array<!proto.bottle.inventory.v1.Component>} value
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListRequest} returns this
*/
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.prototype.setComponentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.bottle.inventory.v1.Component=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bottle.inventory.v1.Component}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.prototype.addComponents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.bottle.inventory.v1.Component, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListRequest} returns this
 */
proto.bottle.inventory.v1.ComponentAvailabilityListRequest.prototype.clearComponentsList = function() {
  return this.setComponentsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.inventory.v1.ComponentAvailabilityListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.inventory.v1.ComponentAvailabilityListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    component: (f = msg.getComponent()) && bottle_inventory_v1_component_pb.Component.toObject(includeInstance, f),
    available: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListResponse}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.inventory.v1.ComponentAvailabilityListResponse;
  return proto.bottle.inventory.v1.ComponentAvailabilityListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.inventory.v1.ComponentAvailabilityListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListResponse}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = new bottle_inventory_v1_component_pb.Component;
      reader.readMessage(value,bottle_inventory_v1_component_pb.Component.deserializeBinaryFromReader);
      msg.setComponent(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAvailable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.inventory.v1.ComponentAvailabilityListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.inventory.v1.ComponentAvailabilityListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getComponent();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      bottle_inventory_v1_component_pb.Component.serializeBinaryToWriter
    );
  }
  f = message.getAvailable();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListResponse} returns this
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Component component = 2;
 * @return {?proto.bottle.inventory.v1.Component}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.prototype.getComponent = function() {
  return /** @type{?proto.bottle.inventory.v1.Component} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_component_pb.Component, 2));
};


/**
 * @param {?proto.bottle.inventory.v1.Component|undefined} value
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListResponse} returns this
*/
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.prototype.setComponent = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListResponse} returns this
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.prototype.clearComponent = function() {
  return this.setComponent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.prototype.hasComponent = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 available = 3;
 * @return {number}
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.prototype.getAvailable = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.bottle.inventory.v1.ComponentAvailabilityListResponse} returns this
 */
proto.bottle.inventory.v1.ComponentAvailabilityListResponse.prototype.setAvailable = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bottle.inventory.v1.LocationListRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.inventory.v1.LocationListRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.inventory.v1.LocationListRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.inventory.v1.LocationListRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.LocationListRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    locationsList: jspb.Message.toObjectList(msg.getLocationsList(),
    bottle_inventory_v1_location_pb.Location.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.inventory.v1.LocationListRequest}
 */
proto.bottle.inventory.v1.LocationListRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.inventory.v1.LocationListRequest;
  return proto.bottle.inventory.v1.LocationListRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.inventory.v1.LocationListRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.inventory.v1.LocationListRequest}
 */
proto.bottle.inventory.v1.LocationListRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = new bottle_inventory_v1_location_pb.Location;
      reader.readMessage(value,bottle_inventory_v1_location_pb.Location.deserializeBinaryFromReader);
      msg.addLocations(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.inventory.v1.LocationListRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.inventory.v1.LocationListRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.inventory.v1.LocationListRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.LocationListRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLocationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      bottle_inventory_v1_location_pb.Location.serializeBinaryToWriter
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.bottle.inventory.v1.LocationListRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.inventory.v1.LocationListRequest} returns this
 */
proto.bottle.inventory.v1.LocationListRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Location locations = 2;
 * @return {!Array<!proto.bottle.inventory.v1.Location>}
 */
proto.bottle.inventory.v1.LocationListRequest.prototype.getLocationsList = function() {
  return /** @type{!Array<!proto.bottle.inventory.v1.Location>} */ (
    jspb.Message.getRepeatedWrapperField(this, bottle_inventory_v1_location_pb.Location, 2));
};


/**
 * @param {!Array<!proto.bottle.inventory.v1.Location>} value
 * @return {!proto.bottle.inventory.v1.LocationListRequest} returns this
*/
proto.bottle.inventory.v1.LocationListRequest.prototype.setLocationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.bottle.inventory.v1.Location=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bottle.inventory.v1.Location}
 */
proto.bottle.inventory.v1.LocationListRequest.prototype.addLocations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.bottle.inventory.v1.Location, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bottle.inventory.v1.LocationListRequest} returns this
 */
proto.bottle.inventory.v1.LocationListRequest.prototype.clearLocationsList = function() {
  return this.setLocationsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.inventory.v1.LocationListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.inventory.v1.LocationListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.inventory.v1.LocationListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.LocationListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    location: (f = msg.getLocation()) && bottle_inventory_v1_location_pb.Location.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.inventory.v1.LocationListResponse}
 */
proto.bottle.inventory.v1.LocationListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.inventory.v1.LocationListResponse;
  return proto.bottle.inventory.v1.LocationListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.inventory.v1.LocationListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.inventory.v1.LocationListResponse}
 */
proto.bottle.inventory.v1.LocationListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = new bottle_inventory_v1_location_pb.Location;
      reader.readMessage(value,bottle_inventory_v1_location_pb.Location.deserializeBinaryFromReader);
      msg.setLocation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.inventory.v1.LocationListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.inventory.v1.LocationListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.inventory.v1.LocationListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.inventory.v1.LocationListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLocation();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      bottle_inventory_v1_location_pb.Location.serializeBinaryToWriter
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.bottle.inventory.v1.LocationListResponse.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bottle.inventory.v1.LocationListResponse} returns this
 */
proto.bottle.inventory.v1.LocationListResponse.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Location location = 2;
 * @return {?proto.bottle.inventory.v1.Location}
 */
proto.bottle.inventory.v1.LocationListResponse.prototype.getLocation = function() {
  return /** @type{?proto.bottle.inventory.v1.Location} */ (
    jspb.Message.getWrapperField(this, bottle_inventory_v1_location_pb.Location, 2));
};


/**
 * @param {?proto.bottle.inventory.v1.Location|undefined} value
 * @return {!proto.bottle.inventory.v1.LocationListResponse} returns this
*/
proto.bottle.inventory.v1.LocationListResponse.prototype.setLocation = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bottle.inventory.v1.LocationListResponse} returns this
 */
proto.bottle.inventory.v1.LocationListResponse.prototype.clearLocation = function() {
  return this.setLocation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bottle.inventory.v1.LocationListResponse.prototype.hasLocation = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.bottle.inventory.v1);
