// source: bottle/catalog/v1/addon.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.bottle.catalog.v1.Addon', null, global);
goog.exportSymbol('proto.bottle.catalog.v1.Addon.AddonCategory', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bottle.catalog.v1.Addon = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bottle.catalog.v1.Addon, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bottle.catalog.v1.Addon.displayName = 'proto.bottle.catalog.v1.Addon';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bottle.catalog.v1.Addon.prototype.toObject = function(opt_includeInstance) {
  return proto.bottle.catalog.v1.Addon.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bottle.catalog.v1.Addon} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.catalog.v1.Addon.toObject = function(includeInstance, msg) {
  var f, obj = {
    category: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bottle.catalog.v1.Addon}
 */
proto.bottle.catalog.v1.Addon.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bottle.catalog.v1.Addon;
  return proto.bottle.catalog.v1.Addon.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bottle.catalog.v1.Addon} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bottle.catalog.v1.Addon}
 */
proto.bottle.catalog.v1.Addon.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.bottle.catalog.v1.Addon.AddonCategory} */ (reader.readEnum());
      msg.setCategory(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bottle.catalog.v1.Addon.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bottle.catalog.v1.Addon.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bottle.catalog.v1.Addon} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bottle.catalog.v1.Addon.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCategory();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.bottle.catalog.v1.Addon.AddonCategory = {
  ADDON_CATEGORY_UNSPECIFIED: 0,
  ADDON_CATEGORY_RUSH_ASSEMBLY: 1,
  ADDON_CATEGORY_HANDLING: 2,
  ADDON_CATEGORY_EWASTE: 3,
  ADDON_CATEGORY_EXTENDED_WARRANTY: 4,
  ADDON_CATEGORY_SHIPPING: 5,
  ADDON_CATEGORY_SOFTWARE_MAINTENANCE: 6
};

/**
 * optional AddonCategory category = 1;
 * @return {!proto.bottle.catalog.v1.Addon.AddonCategory}
 */
proto.bottle.catalog.v1.Addon.prototype.getCategory = function() {
  return /** @type {!proto.bottle.catalog.v1.Addon.AddonCategory} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.bottle.catalog.v1.Addon.AddonCategory} value
 * @return {!proto.bottle.catalog.v1.Addon} returns this
 */
proto.bottle.catalog.v1.Addon.prototype.setCategory = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


goog.object.extend(exports, proto.bottle.catalog.v1);
